name: covid19-metatx
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastqc=0.12.0
  - multiqc=1.14
  - cutadapt=1.18
  - bwa=0.7.17
  - samtools>=1.16
  - qualimap=2.2.1
  - spades=3.15.3
  - mafft=7.471
  - nextclade=1.5.3
  - lofreq=2.1.5
  - snpeff
  - subread=2.0.1        # provides featureCounts
  - bowtie2=2.4.5
  - vsearch=2.22.0
  - metaphlan=4.0.6
  - pandas
  - matplotlib
  - seaborn
  - r-base>=4.2
  - bioconductor-deseq2
  - r-vegan
  - r-tidyverse
  - r-optparse
  - pip
  - pip:
      - multiqc==1.14
